Repository dotnet/SqlClient, pull requests merged in 2020-11, with the labels that each got.

#797 Related samples to ADO.NET documents, importing from .NET Framework-Part 1
  doc/samples/ConnectionStringSettings_RetrieveFromConfig.cs
  doc/samples/ConnectionStringSettings_RetrieveFromConfigByName.cs
  doc/samples/ConnectionStringSettings_RetrieveFromConfigByProvider.cs
  doc/samples/ConnectionStringsWeb_Encrypt.cs
  doc/samples/ConnectionStrings_Encrypt.cs
  doc/samples/SqlCommand_StoredProcedure.cs
  doc/samples/SqlConnectionStringBuilder_InjectionAttack.cs
  doc/samples/SqlConnectionStringBuilder_UserNamePwd.cs
  doc/samples/SqlConnection_InfoMessage_StateChange.cs
  doc/samples/SqlConnection_Pooling.cs
  doc/samples/SqlConnection_Pooling_Use_Statement.cs
Labels: :page_with_curl: Documentation

#800 Introduce new API to clear global Public Client Application instances holding User Token Cache
  doc/snippets/Microsoft.Data.SqlClient/ActiveDirectoryAuthenticationProvider.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
Labels: :new: Public API

#796 Fixes "InvalidOperationException" errors by performing async operations in SemaphoreSlim
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNINpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIStreams.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SslOverTdsStream.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AsyncTest/AsyncCancelledConnectionsTest.cs
Labels: :chart_with_upwards_trend: Performance

#821 Related samples to ADO.NET documents, importing from .NET Framework-Part 2
  doc/samples/SqlCommandBuilder_Create.cs
  doc/samples/SqlCommand_ExecuteNonQuery_SP_DML.cs
  doc/samples/SqlCommand_ExecuteScalar_Return_Id.cs
  doc/samples/SqlDataAdapter_FillDataSet.cs
  doc/samples/SqlDataAdapter_SqlDataAdapter.cs
  doc/samples/SqlDataReader_GetSchemaTable.cs
  doc/samples/SqlDataReader_HasRows.cs
  doc/samples/SqlDataReader_NextResult.cs
Labels: :page_with_curl: Documentation

#824 Add more code samples for documentation - Transaction and GetSchema
  doc/samples/SqlConnection_GetSchema_Restriction.cs
  doc/samples/SqlConnection_GetSchema_Tables.cs
  doc/samples/SqlDataAdapter_Concurrency.cs
  doc/samples/SqlTransactionLocal.cs
  doc/samples/SqlTransactionScope.cs
Labels: :page_with_curl: Documentation
