Repository dotnet/SqlClient, pull requests merged in 2020-07, with the labels that each got.

#499 perf: Move datareader caches down to internal connection
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
Labels: Port to NetFx

#626 Feature | Add support for Data Classification v2
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/ColumnSensitivity.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/InformationType.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/Label.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityClassification.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityProperty.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityRank.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/DataClassification/SensitivityClassification.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataClassificationTest/DataClassificationTest.cs
Labels: :new: Public API

#528 perf: Rework ExecuteReaderAsync to minimize allocations
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/AAsyncCallContext.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :chart_with_upwards_trend: Performance

#597 Introduce support for AAD Device Code Flow authentication
  doc/samples/AADAuthenticationCustomDeviceFlowCallback.cs
  doc/samples/CustomDeviceCodeFlowAzureAuthenticationProvider.cs
  doc/snippets/Microsoft.Data.SqlClient/ActiveDirectoryAuthenticationProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationMethod.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationProvider.xml
  src/Microsoft.Data.SqlClient.sln
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.NetStandard.cs
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.NetStandard.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/SR.Designer.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/SR.resx
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AADAuthenticationTests.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
Labels: :new: Public API
