Repository dotnet/SqlClient, pull requests merged in 2022-11, with the labels that each got.

#1812 Port SqlParameter changes from netcore to netfx
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
Labels: :heavy_plus_sign: Code Health

#1813 Add support for DateOnly and TimeOnly (SqlParameter value and GetFieldValue(Async) )
  doc/snippets/Microsoft.Data.SqlClient/SqlDataReader.xml
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlParameterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/ProviderAgnostic/ReaderTest/ReaderTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DateTimeTest/DateTimeTest.cs
Labels: netcore

#1831 Update native SNI version
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_facing_up: Native SNI

#1822 TDS8 Add Server Certificate Support
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/StringsHelper.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs
Labels: :new: Public API

#1842 Test | Fix akvtest issues
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/AKVTests.cs
Labels: :heavy_check_mark: Tests
