Repository dotnet/SqlClient, pull requests merged in 2022-09, with the labels that each got.

#1756 4.0.2 release notes [main branch]
  CHANGELOG.md
  release-notes/4.0/4.0.2.md
  release-notes/4.0/4.0.md
  release-notes/4.0/README.md
Labels: :page_with_curl: Documentation

#1760 [Hotfix 4.0.2] | Release notes
  CHANGELOG.md
  release-notes/4.0/4.0.2.md
  release-notes/4.0/4.0.md
  release-notes/4.0/README.md
Labels: :page_with_curl: Documentation

#1759 4.1.1 release notes [main branch]
  CHANGELOG.md
  release-notes/4.1/4.1.1.md
  release-notes/4.1/4.1.md
  release-notes/4.1/README.md
Labels: :page_with_curl: Documentation

#1761 [Hotfix 4.1.1] | Release notes
  CHANGELOG.md
  release-notes/4.1/4.1.1.md
  release-notes/4.1/4.1.md
  release-notes/4.1/README.md
Labels: :page_with_curl: Documentation

#1769 Porting guide addition
  porting-cheat-sheet.md
Labels: :page_with_curl: Documentation

#1771 Make SqlConnectionEncryptOption string parser public
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionEncryptOption.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionEncryptOption.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
Labels: :new: Public API

#1768 For failed connection requests in ConnectionPool in case of PoolBlock…
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
Labels: :bulb: Enhancement, netcore
