Repository dotnet/SqlClient, pull requests merged in 2022-02, with the labels that each got.

#1493 [4.1.0] | Release notes 4.1.0
  CHANGELOG.md
  release-notes/4.1/4.1.0.md
  release-notes/4.1/4.1.md
  release-notes/4.1/README.md
  release-notes/README.md
Labels: :page_with_curl: Documentation

#1488 Release Notes 4.1.0
  CHANGELOG.md
  release-notes/4.1/4.1.0.md
  release-notes/4.1/4.1.md
  release-notes/4.1/README.md
  release-notes/README.md
Labels: :page_with_curl: Documentation

#1492 Doc | Update PersistSecurityInfo Summary
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
Labels: :page_with_curl: Documentation

#1505 Doc | Add detail to Attestation Protocol
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
Labels: :page_with_curl: Documentation

#1513 [4.1] Doc | Add detail to Attestation Protocol
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
Labels: :page_with_curl: Documentation

#1458 Updated Unit Tests for FileStream
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlTypes/SqlFileStream.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/SqlFileStreamTest/SqlFileStreamTest.cs
Labels: :heavy_check_mark: Tests

#1499 Test | Seperate LocalDB and NamedPipe LocalDB Tests
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/LocalDBTest/LocalDBTest.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#1197 Perf: use manual masking on state flags to avoid boxing
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :chart_with_upwards_trend: Performance, netcore

#1518 Fix | Improve code coverage using net fx
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlSer.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlDataRecordTest.cs
Labels: :heavy_plus_sign: Code Health

#1351 Clean: Modernize style in ValueUtilsSmi
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReaderSmi.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.netcore.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.netfx.cs
Labels: :heavy_plus_sign: Code Health

#1503 Add Microsoft.SqlServer.Server documentation
  doc/samples/Microsoft.SqlServer.Server/csharp/DataWorks_IBinarySerialize_Sample.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/DataWorks_SqlFunctionAttribute_Sample.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/DataWorks_SqlUserDefinedAggregateAttribute_Sample.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/DataWorks_SqlUserDefinedTypeAttribute_Sample.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/SqlFunctionAttribute_SqlFunction.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/SqlMethod.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/SqlUserDefinedAggregateAttribute_Aggregate1.cs
  doc/samples/Microsoft.SqlServer.Server/csharp/SqlUserDefinedTypeAttribute_Type1.cs
  doc/samples/Microsoft.SqlServer.Server/visualbasic/DataWorks_IBinarySerialize_Sample.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/DataWorks_SqlFunctionAttribute_Sample.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/DataWorks_SqlUserDefinedAggregateAttribute_Sample.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/DataWorks_SqlUserDefinedTypeAttribute_Sample.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/SqlFunctionAttribute_SqlFunction.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/SqlUserDefinedAggregateAttribute_Aggregate1.vb
  doc/samples/Microsoft.SqlServer.Server/visualbasic/SqlUserDefinedTypeAttribute_Type1.vb
  doc/snippets/Microsoft.Data.SqlClient.Server/InvalidUdtException.xml
  doc/snippets/Microsoft.SqlServer.Server/DataAccessKind.xml
  doc/snippets/Microsoft.SqlServer.Server/Format.xml
  doc/snippets/Microsoft.SqlServer.Server/IBinarySerialize.xml
  doc/snippets/Microsoft.SqlServer.Server/InvalidUdtException.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlFacetAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlFunctionAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlMethodAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlUserDefinedAggregateAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlUserDefinedTypeAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SystemDataAccessKind.xml
  src/Microsoft.SqlServer.Server/IBinarySerialize.cs
  src/Microsoft.SqlServer.Server/InvalidUdtException.cs
  src/Microsoft.SqlServer.Server/SqlFacetAttribute.cs
  src/Microsoft.SqlServer.Server/SqlFunctionAttribute.cs
  src/Microsoft.SqlServer.Server/SqlMethodAttribute.cs
  src/Microsoft.SqlServer.Server/SqlUserDefinedAggregateAttribute.cs
  src/Microsoft.SqlServer.Server/SqlUserDefinedTypeAttribute.cs
  src/Microsoft.SqlServer.Server/TypeForwards.cs
Labels: :page_with_curl: Documentation
