Repository dotnet/SqlClient, pull requests merged in 2022-10, with the labels that each got.

#1778 Fix | NRE on assigning null to SqlConnectionStringBuilder.Encrypt
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionEncryptOption.xml
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
Labels: :bug: Bug!

#1766 Fix async deadlock issue when sending attention fails due to network failure
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :bug: Bug!

#1443 Port lazy initialize hidden column map to netfx
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
Labels: netfx, :heavy_plus_sign: Code Health

#1604 Merge to shared - TdsParserSafeHandles
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
Labels: :heavy_plus_sign: Code Health

#1595 Merge to shared - TdsParserSessionPool
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserSessionPool.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSessionPool.cs
Labels: :heavy_plus_sign: Code Health

#1795 [5.0.1] | Update SNI version
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_facing_up: Native SNI

#1802 [Hotfix 5.0.1] | Release notes
  CHANGELOG.md
  release-notes/5.0/5.0.1.md
  release-notes/5.0/5.0.md
  release-notes/5.0/README.md
Labels: :page_with_curl: Documentation

#1817 Test | Fix Mac OS test failures
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests
