Repository dotnet/SqlClient, pull requests merged in 2022-04, with the labels that each got.

#1542 Improvment | Remove unnecessary netcoreapp2.1 constant from the driver
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
Labels: :bulb: Enhancement

#1559 Fix | Skip the CRL check during authenticaiton
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNINpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
Labels: :m: Managed SNI

#1438 Share SqlBuffer
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBuffer.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
Labels: :heavy_plus_sign: Code Health

#1371 Merge to Shared for DbConnectionPoolGroup
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionPoolGroup.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolGroup.cs
Labels: :heavy_plus_sign: Code Health

#1370 Move to Shared for SqlDependencyUtils.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.AppDomain.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.AssemblyLoadContext.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.cs
Labels: :heavy_plus_sign: Code Health

#1483 Move to Shared for TdsEnums.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsEnums.cs
Labels: :heavy_plus_sign: Code Health

#1343 Move to Shared SqlSequentialTextReader
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlSequentialTextReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlSequentialTextReader.cs
Labels: :heavy_plus_sign: Code Health

#1574 DEV | Drop support for Net461 and add support for Net462
  BUILDGUIDE.md
  README.md
  RunTests.cmd
  src/Microsoft.Data.SqlClient/add-ons/Directory.Build.props
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/System/Net/Logging/NetEventSource.Common.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.de.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.es.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.fr.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.it.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.ja.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.ko.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.pt-BR.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.ru.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.zh-Hans.resx
  src/Microsoft.Data.SqlClient/netfx/src/Resources/Strings.zh-Hant.resx
  src/Microsoft.Data.SqlClient/tests/Directory.Build.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
  tools/specs/Microsoft.SqlServer.Server.nuspec
  tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec
Labels: netfx

#1582 [2.1] Changes to run tests on 1es pipelines
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/CspProviderExt.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/CertificateUtilityWin.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/TcpDefaultForAzureTest.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#1586 [Docs] Add version details for Attestation Protocol and Encrypt in SqlConnection.ConnectionString
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
Labels: :page_with_curl: Documentation
