Repository dotnet/SqlClient, pull requests merged in 2022-07, with the labels that each got.

#1676 [BrokenLinksH2] Fix path in link
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
Labels: :page_with_curl: Documentation

#1673 Doc | Configurable Retry Logic doesn't support CommandBehavior.CloseConnection
  doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionEncryptOption.xml
Labels: :page_with_curl: Documentation

#1671 Changing Encoding UTF7 to ASCII for SSRP Broadcast
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SSRP.cs
Labels: :m: Managed SNI

#1677 Doc | Fix a link
  doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml
Labels: :page_with_curl: Documentation

#1657 Adding TDS8 version for TDSLogin
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsEnums.cs
Labels: :bug: Bug!
