Repository dotnet/SqlClient, pull requests merged in 2023-03, with the labels that each got.

#1926 Backport 3.1.x Fix | Throttling of token requests by calling AcquireTokenSilent
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
Labels: :bulb: Enhancement

#1939 Backport 3.1.x Fix | TDS RPC error on large queries in SqlCommand.ExecuteReaderAsync
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ApiShould.cs
Labels: :bug: Bug!, netfx

#1950 Fix Linux code coverage result in Build proj
  build.proj
Labels: :bulb: Enhancement

#1951 Release Notes M.D.S v3.1.3
  CHANGELOG.md
  release-notes/3.1/3.1.3.md
  release-notes/3.1/3.1.md
  release-notes/3.1/README.md
Labels: :page_with_curl: Documentation

#1925 Fix | Throttling of token requests by calling AcquireTokenSilent
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
Labels: :bulb: Enhancement

#1936 Fix | TDS RPC error on large queries in SqlCommand.ExecuteReaderAsync
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ApiShould.cs
Labels: :bug: Bug!, netfx

#1943 Replace calls to `Method.GetCurrentMethod().Name` with `nameof()`
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicManager.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAppContextSwitchManager.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicManager.LoadType.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalAppContextSwitches.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/AppConfigManager.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/Common/SqlRetryLogic.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/Common/SqlRetryLogicProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicLoader.cs
Labels: :heavy_plus_sign: Code Health

#1948 Fix | Addressing failure on providing correct error message when symmetric key decryption fails using Always Encrypted.
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: :bug: Bug!

#1969 Fix order
  release-notes/README.md
Labels: :page_with_curl: Documentation

#1970 Release notes v5.1.1
  CHANGELOG.md
  release-notes/5.1/5.1.1.md
  release-notes/5.1/5.1.md
  release-notes/5.1/README.md
Labels: :page_with_curl: Documentation

#1979 Release notes 5.0.2
  CHANGELOG.md
  release-notes/5.0/5.0.2.md
  release-notes/5.0/5.0.md
  release-notes/5.0/README.md
Labels: :page_with_curl: Documentation
