Repository dotnet/SqlClient, pull requests merged in 2023-10, with the labels that each got.

#2186 Remove stale dependencies from SqlClient
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: netcore

#2189 Fix | Upgrade dependencies versions.
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :bulb: Enhancement

#2164 Merge TDSParserStateObject.StateSnapshot packet list mangement and reimplment
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :bulb: Enhancement, :heavy_plus_sign: Code Health

#2194 Fix | Support Georgian collation
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataReaderTest/DataReaderTest.cs
Labels: :bug: Bug!

#2197 [5.1.2] Release notes
  CHANGELOG.md
  release-notes/5.1/5.1.2.md
  release-notes/5.1/5.1.md
  release-notes/5.1/README.md
Labels: :page_with_curl: Documentation

#2199 [4.0.4] Release notes
  CHANGELOG.md
  release-notes/4.0/4.0.4.md
  release-notes/4.0/4.0.md
  release-notes/4.0/README.md
Labels: :page_with_curl: Documentation

#2200 [3.1.4] Release notes
  CHANGELOG.md
  release-notes/3.1/3.1.4.md
  release-notes/3.1/3.1.md
  release-notes/3.1/README.md
Labels: :page_with_curl: Documentation
