Repository dotnet/SqlClient, pull requests merged in 2023-07, with the labels that each got.

#2073 Code Merge | TdsParserStateObject alignment
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSessionPool.cs
Labels: :heavy_plus_sign: Code Health

#2057 Fix | Adding type convertor support for SqlConnectionEncryptOption
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionEncryptOption.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionEncryptOptionConverter.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
  tools/props/Versions.props
Labels: :bug: Bug!

#2047 Support SuperSocketNetLib registry option for Encrypt on NetCore Windows
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
Labels: netcore

#1959 Fix bunch of annontations
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicLoader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiMetaData.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.netcore.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlMetaData.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlNormalizer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlSer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
Labels: :bulb: Enhancement, netcore

#2084 Fix retry with SqlDataAdapter.Fill(SqlDataTable) on .NET Framework
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
Labels: :bug: Bug!, netfx

#2088 Remove redundant TdsParserSafeHandles.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.cs
Labels: :heavy_plus_sign: Code Health

#2090 Test | Fix TdsParserStateObjectHelper debug mode
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/Common/SystemDataInternals/TdsParserStateObjectHelper.cs
Labels: :heavy_check_mark: Tests

#2094 Release Notes v5.2 preview 3
  CHANGELOG.md
  release-notes/5.2/5.2.0-preview3.md
  release-notes/5.2/5.2.0.md
  release-notes/5.2/README.md
Labels: :page_with_curl: Documentation

#2093 Fix .NET and .NET Standard file version
  tools/props/Versions.props
Labels: :bug: Bug!, netcore

#2097 Minor changes to 5.2 preview 3 release notes
  CHANGELOG.md
  release-notes/5.2/5.2.0-preview3.md
Labels: :page_with_curl: Documentation
