Repository dotnet/SqlClient, pull requests merged in 2023-04, with the labels that each got.

#1974 Fix | Dropping reference to Microsoft.Win32.Registry in netcore.
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: netcore

#1931 Enable SqlDiagnosticListener on .NET Standard
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDiagnosticListener.NetStandard.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDiagnosticListener.cs
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: netcore

#1973 Update NuGet package description
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_with_curl: Documentation

#1998 Test | Disable SqlConnectionReliabilityTest.ConcurrentExecution test
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2002 [4.0.3] | Update NuGet package description (#1973)
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_with_curl: Documentation

#1997 Fix activity correlator to continue using same GUID for connection activity
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ActivityCorrelator.cs
Labels: :bug: Bug!

#2007 Release notes - Hotfix v4.0.3
  CHANGELOG.md
  release-notes/4.0/4.0.3.md
  release-notes/4.0/4.0.md
  release-notes/4.0/README.md
Labels: :page_with_curl: Documentation

#2009 Documentation | Release Notes 5.2.0-preview1
  CHANGELOG.md
  release-notes/5.2/5.2.0-preview1.md
  release-notes/5.2/5.2.0.md
  release-notes/5.2/README.md
  tools/props/Versions.props
Labels: :page_with_curl: Documentation

#2014 [2.1.6] | Update NuGet package description (#1973)
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_with_curl: Documentation

#2023 Release notes v2.1.6
  CHANGELOG.md
  release-notes/2.1/2.1.6.md
  release-notes/2.1/2.1.md
  release-notes/2.1/README.md
  release-notes/README.md
Labels: :page_with_curl: Documentation

#2018 Fix | Adding non-string support to SqlConnectionStringBuilder property indexer
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionEncryptOption.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
Labels: :bug: Bug!
