Repository dotnet/SqlClient, pull requests merged in 2023-06, with the labels that each got.

#2045 Fix | Minor fixes to support different test environments
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SSRP.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ApiShould.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/BulkCopyAE.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/BulkCopyAEErrorMessage.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/End2EndSmokeTests.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/SqlBulkCopyTruncation.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/SqlNullValues.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/IntegratedAuthenticationTest/IntegratedAuthenticationTest.cs
Labels: :heavy_check_mark: Tests, netcore

#2031 Update Microsoft.Identity.Client package version
  tools/props/Versions.props
Labels: :bulb: Enhancement

#1934 Add net8 compatibility
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlTypes/SqlTypeWorkarounds.netcore.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
Labels: :bulb: Enhancement

#2054 Test | Replacing try/catch with xUnit Throws.
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
Labels: :heavy_check_mark: Tests

#2056 Release notes - 5.2.0-preview2
  CHANGELOG.md
  release-notes/5.2/5.2.0-preview2.md
  release-notes/5.2/5.2.0.md
  release-notes/5.2/README.md
  release-notes/README.md
Labels: :page_with_curl: Documentation

#2058 Fix | SqlDataSourceEnumeratorTest correct ConditionalFact
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/SqlDSEnumeratorTest/SqlDataSourceEnumeratorTest.cs
Labels: :heavy_check_mark: Tests

#2071 Code Health | Improve TdsParser
  src/Microsoft.Data.SqlClient/netcore/src/Common/Common.Tests.sln
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/System/PasteArguments.Unix.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/System/PasteArguments.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/System/PasteArguments.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/tests/System/Collections/DictionaryExtensions.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/Common/InternalConnectionWrapper.cs
Labels: :heavy_plus_sign: Code Health

#2066 Fix th-TH culture info issue on Managed SNI
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
Labels: :m: Managed SNI

#2063 Dev | Add support of the new authentication API with SSPI token on Managed SNI
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Interop/Windows/Interop.Libraries.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
Labels: :m: Managed SNI
