Repository dotnet/SqlClient, pull requests merged in 2023-09, with the labels that each got.

#2060 Update | Update SSL certificate error messages
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectionTestWithSSLCert/CertificateTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectionTestWithSSLCert/GenerateSelfSignedCertificate.ps1
Labels: :m: Managed SNI

#2129 Fix | LocalDb and managed SNI
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/LocalDB.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/LocalDBTest/LocalDBTest.cs
Labels: :bug: Bug!, :m: Managed SNI

#2144 Merge TDSParserStateObject.StateSnapshot creation and clearing
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :heavy_plus_sign: Code Health

#2145 Test | Fixing MARS manual tests on some debug field's name change
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/Common/SystemDataInternals/TdsParserStateObjectHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/MARSTest/MARSTest.cs
Labels: :heavy_check_mark: Tests

#2147 SDL | Changing ReadXml to a more secure overload.
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbMetaDataFactory.cs
Labels: :bulb: Enhancement

#2132 Merge TDSParserStateObject.StateSnapshot state flags
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :heavy_plus_sign: Code Health

#2153 Doc | Move attestation protocol remark to the correct place
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
Labels: :page_with_curl: Documentation
