Repository dotnet/SqlClient, pull requests merged in 2023-08, with the labels that each got.

#2118 Update docs to include note about existing issues with Async APIs
  doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDataReader.xml
Labels: :page_with_curl: Documentation

#2110 Consolidation of localization
  build.proj
  src/Directory.Build.props
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/netcore/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/netcore/src/Resources/StringsHelper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/tools/targets/GenerateResourceStringsSource.targets
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.de.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.es.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.fr.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.it.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.ja.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.ko.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.pt-BR.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.ru.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.zh-Hans.resx
  src/Microsoft.Data.SqlClient/src/Resources/Strings.zh-Hant.resx
  src/Microsoft.Data.SqlClient/src/Resources/StringsHelper.cs
  src/Microsoft.Data.SqlClient/src/tools/scripts/GenerateResourceStringsSource.ps1
  src/Microsoft.Data.SqlClient/src/tools/targets/GenerateResourceStringsSource.targets
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/LocalizationTest.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :bulb: Enhancement

#2123 Update native SNI version
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_facing_up: Native SNI

#2121 Make array rental return after TryReadPlpUnicodeChars unconditional
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: :chart_with_upwards_trend: Performance

#2098 Dev | Improved connection timeout
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNINpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SSRP.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/TimeoutTimer.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
Labels: :bulb: Enhancement
