Repository dotnet/SqlClient, pull requests merged in 2024-07, with the labels that each got.

#2646 Test fixes to accommodate recent infra changes
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataBaseSchemaTest/ConnectionSchemaTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConfigurationManagerReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2650 [5.2] Test fixes to accommodate recent infra changes
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataBaseSchemaTest/ConnectionSchemaTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConfigurationManagerReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :bug: Bug!, :heavy_check_mark: Tests

#2651 Fix - Don't error when using infinte connect timeout and Entra auth
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
Labels: :bug: Bug!

#2653 eng | Add delay signed to official builds
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2575 eng | Initial YAML CI pipeline
  build.proj
  eng/pipelines/common/templates/jobs/ci-build-nugets-job.yml
  eng/pipelines/common/templates/jobs/ci-code-coverage-job.yml
  eng/pipelines/common/templates/jobs/ci-run-tests-job.yml
  eng/pipelines/common/templates/stages/ci-run-tests-stage.yml
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/build-all-tests-step.yml
  eng/pipelines/common/templates/steps/ci-prebuild-step.yml
  eng/pipelines/common/templates/steps/ci-project-build-step.yml
  eng/pipelines/common/templates/steps/configure-sql-server-linux-step.yml
  eng/pipelines/common/templates/steps/configure-sql-server-step.yml
  eng/pipelines/common/templates/steps/configure-sql-server-win-step.yml
  eng/pipelines/common/templates/steps/generate-nuget-package-step.yml
  eng/pipelines/common/templates/steps/publish-test-results-step.yml
  eng/pipelines/common/templates/steps/run-all-tests-step.yml
  eng/pipelines/common/templates/steps/update-config-file-step.yml
  eng/pipelines/common/templates/steps/update-nuget-config-local-feed-step.yml
  eng/pipelines/dotnet-sqlclient-ci-core.yml
  eng/pipelines/dotnet-sqlclient-ci-package-reference-pipeline.yml
  eng/pipelines/dotnet-sqlclient-ci-project-reference-pipeline.yml
  eng/pipelines/libraries/ci-build-variables.yml
Labels: Infrastructure

#2684 eng | Add Delay sign to ref csprojs
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bulb: Enhancement, Infrastructure

#2691 eng | Set DisableSourceLinkTranslation to false
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
Labels: Infrastructure

#2698 eng | Address strong naming issues in created nugets
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: Infrastructure

#2663 TDS Reader implementation
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/ITdsReadStream.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/TdsBufferManager.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/TdsReadStream.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/TdsReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/TdsStream.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/IO/TdsWriter.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/Handlers/Prelogin/PreloginHandlerTest.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsHelpers/SplittableStream.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsHelpers/TdsMessage.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsHelpers/TdsServerPacket.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsHelpers/TdsUtils.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsReadStreamTest.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsReaderTest.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/IO/TdsWriterTests.cs
Labels: ClientX

#2699 Fix macOS CI
  eng/pipelines/dotnet-sqlclient-ci-core.yml
Labels: :heavy_check_mark: Tests

#2706 [5.1] Test fixes to accommodate recent infra changes
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataBaseSchemaTest/ConnectionSchemaTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConfigurationManagerReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2707 [4.0] Test fixes to accommodate recent infra changes
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataBaseSchemaTest/ConnectionSchemaTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConfigurationManagerReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :bug: Bug!, :heavy_check_mark: Tests

#2709 [3.1] Test fixes to accommodate recent infra changes
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AdapterTest/AdapterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/AADConnectionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataBaseSchemaTest/ConnectionSchemaTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConfigurationManagerReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :bug: Bug!, :heavy_check_mark: Tests

#2713 Minor adjustment to sourcelink translation
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  src/Directory.Build.props
  tools/targets/RepositoryInfo.targets
Labels: :heavy_plus_sign: Code Health

#2725 FIX | Revert the change to TargetFrameworkMonikerAssemblyAttributesPath from PR #2497
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2636 Avoid "early" access to SqlAuthenticationProviderManager.Instance
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
Labels: :bulb: Enhancement, netcore

#2718 [5.2] Fix | Enable source link translation
  src/Directory.Build.props
  tools/targets/RepositoryInfo.targets
Labels: :bug: Bug!

#2726 Replace unused out arguments with discards
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Interop/Windows/sspicli/SSPIWrapper.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Interop/Windows/sspicli/SecuritySafeHandles.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/DBConnectionString.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlTypes/SqlFileStream.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbReferenceCollection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/AzureAttestationBasedEnclaveProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SQLFallbackDNSCache.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalTransaction.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RandomStressTest/Randomizer.cs
Labels: :heavy_plus_sign: Code Health

#2701 [5.2] eng | Address strong naming issues in created nugets
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2720 [4.0] eng | Secure symbols publishing
  eng/pipelines/common/templates/jobs/build-signed-akv-package-job.yml
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/run-tests-package-reference-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
  eng/pipelines/common/templates/steps/esrp-code-signing-step.yml
  eng/pipelines/common/templates/steps/publish-symbols-step.yml
  eng/pipelines/dotnet-sqlclient-signing-pipeline.yml
  eng/pipelines/libraries/common-variables.yml
Labels: Infrastructure

#2719 [5.1] eng | Secure symbols publishing
  eng/pipelines/common/templates/jobs/build-signed-akv-package-job.yml
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/run-tests-package-reference-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
  eng/pipelines/common/templates/steps/esrp-code-signing-step.yml
  eng/pipelines/common/templates/steps/publish-symbols-step.yml
  eng/pipelines/dotnet-sqlclient-signing-pipeline.yml
  eng/pipelines/libraries/common-variables.yml
Labels: Infrastructure

#2717 [5.2] eng | Secure symbols publishing
  eng/pipelines/common/templates/jobs/build-signed-akv-package-job.yml
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/run-tests-package-reference-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
  eng/pipelines/common/templates/steps/publish-symbols-step.yml
  eng/pipelines/dotnet-sqlclient-signing-pipeline.yml
  eng/pipelines/libraries/mds-variables.yml
Labels: Infrastructure

#2652 Fix | Fixed some Azure managed identity authentication unit test failures
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicTestHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2702 [5.1] eng | Address strong naming issues in created nugets #2698
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!, Infrastructure
