Repository dotnet/SqlClient, pull requests merged in 2024-02, with the labels that each got.

#2334 Fix | Adding missing commitID to AKV nuspec
  tools/specs/Microsoft.SqlServer.Server.nuspec
  tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec
Labels: :package: AKV Provider

#2327 Release notes 5.1.5
  CHANGELOG.md
  release-notes/5.1/5.1.5.md
  release-notes/5.1/5.1.md
  release-notes/5.1/README.md
Labels: :page_with_curl: Documentation

#2349 Fix | Mismatch System.Diagnostics.DiagnosticSource between versions.props and nuspec
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :heavy_check_mark: Tests, netcore

#2351 Doc | Update Release Documentation for Contributors
  release-notes/5.0/5.0.0-preview1.md
  release-notes/5.0/5.0.0-preview2.md
  release-notes/5.0/5.0.0-preview3.md
  release-notes/5.0/5.0.0.md
  release-notes/5.0/5.0.1.md
  release-notes/5.0/5.0.2.md
  release-notes/5.1/5.1.0-preview1.md
  release-notes/5.1/5.1.0-preview2.md
  release-notes/5.1/5.1.0.md
  release-notes/5.1/5.1.1.md
  release-notes/5.1/5.1.2.md
  release-notes/5.1/5.1.3.md
  release-notes/5.1/5.1.4.md
  release-notes/5.1/5.1.5.md
  release-notes/5.2/5.2.0-preview1.md
  release-notes/5.2/5.2.0-preview2.md
  release-notes/5.2/5.2.0-preview3.md
  release-notes/5.2/5.2.0-preview4.md
  release-notes/5.2/5.2.0-preview5.md
Labels: :page_with_curl: Documentation

#2347 SDL | Removing DSA public key from SqlColumnEncryptionProvider to address CodeQL flag
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlColumnEncryptionCertificateStoreProvider.Windows.cs
Labels: :bulb: Enhancement

#2345 Test | Docker test enhancement
  src/Microsoft.Data.SqlClient/tests/Docker/DockerLinuxTest/Dockerfile
  src/Microsoft.Data.SqlClient/tests/Docker/DockerLinuxTest/Microsoft.Data.SqlClient.DockerLinuxTest.csproj
  src/Microsoft.Data.SqlClient/tests/Docker/DockerLinuxTest/Program.cs
  src/docker-compose.dcproj
  src/docker-compose.override.yml
  src/docker-compose.yml
Labels: :heavy_check_mark: Tests

#2363 Change | Updating SNI version to 5.2.0
  src/Microsoft.Data.SqlClient/tests/Directory.Build.props
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_facing_up: Native SNI

#2367 Test | Adjust tests to read IsAzureSynapse value from database
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
Labels: :heavy_check_mark: Tests

#2281 Fix | Fix unit test for SPN to include port number with Managed SNI
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
Labels: :m: Managed SNI

#2371 Fix | Refine documents for GA v5.2
  doc/snippets/Microsoft.Data.Common/DbBatch.xml
  doc/snippets/Microsoft.Data.Common/DbBatchCommand.xml
  doc/snippets/Microsoft.Data.Common/DbBatchCommandCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatch.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatchCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatchCommandCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopy.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlException.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/ref/Microsoft.Data.SqlClient.Batch.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/ref/Microsoft.Data.SqlClient.Batch.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatch.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatchCommand.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatchCommandCollection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlException.cs
Labels: :new: Public API, :page_with_curl: Documentation

#2372 Fix | ExecuteReaderAsync API return type in ref file
  src/Microsoft.Data.SqlClient/ref/Microsoft.Data.SqlClient.Batch.cs
Labels: :new: Public API
