Repository dotnet/SqlClient, pull requests merged in 2024-04, with the labels that each got.

#2428 Fix | Suppress CodeQL warning for usage of deprecated Ssl2.
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
Labels: :heavy_plus_sign: Code Health

#2440 Doc | update a sample description in SqlConnection
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
Labels: :page_with_curl: Documentation

#2450 eng | Fix production pipeline
  eng/pipelines/common/templates/steps/update-nuget-config-local-feed-step.yml
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
Labels: Infrastructure

#2356 Rent byte buffers in SqlSequentialTextReader
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlSequentialTextReader.cs
Labels: :bulb: Enhancement

#2310 Fix | SqlBuffer.SqlGuid
  .gitignore
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlBufferTests.cs
Labels: :bug: Bug!

#2448 Fix | ArgumentNullException on SqlDataRecord.GetValue when using Udt data type
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/MetadataUtilsSmi.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlDataRecordTest.cs
Labels: :bug: Bug!, netcore

#2467 [5.2.1] | Fix CodeQL and Rozlyn warnings (#2428) and (#2432)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
Labels: :heavy_plus_sign: Code Health

#2469 Test | Address XUnit failure on Windows Principal functionality is not supported on this platform
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/SqlColumnEncryptionCertificateStoreProviderShould.cs
Labels: :heavy_check_mark: Tests

#2462 Change | Updating Azure.Identity version to 1.11.2
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
  tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec
Labels: :bulb: Enhancement
