Repository dotnet/SqlClient, pull requests merged in 2024-11, with the labels that each got.

#2828 Remove unused PInvokes
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/AdapterSwitches.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/NativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/SafeNativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/UnsafeNativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperARM64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX86.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlTypes/UnsafeNativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Misc/ExternDll.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Interop.Libraries.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
Labels: :heavy_plus_sign: Code Health

#2938 Clean up Preprocessor Directives After NET6 Removal
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.AssemblyLoadContext.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlTransaction.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/OperationAbortedException.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/AlwaysEncryptedKeyConverter.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalAppContextSwitches.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicLoader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ExtendedClrTypeCode.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/MetadataUtilsSmi.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiMetaData.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlDataRecord.netcore.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlMetaData.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlNormalizer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlSer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatch.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatchCommand.Net8OrGreater.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatchCommand.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBatchCommandCollection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyListener.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.AssemblyLoadContext.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlException.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsValueSetter.cs
  src/Microsoft.Data.SqlClient/src/Resources/StringsHelper.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/SqlColumnEncryptionCertificateStoreProviderShould.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/SqlColumnEncryptionCngProviderShould.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/SqlColumnEncryptionCspProviderShould.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlBufferTests.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlParameterTest.cs
Labels: :heavy_plus_sign: Code Health

#2945 Upgrade code coverage job to net 8.
  eng/pipelines/common/templates/jobs/ci-code-coverage-job.yml
Labels: :heavy_plus_sign: Code Health

#2973 Switch mac image to latest tag
  eng/pipelines/dotnet-sqlclient-ci-core.yml
Labels: :heavy_plus_sign: Code Health

#2954 Align newlines between netfx and netcore
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2958 Align keyword ordering and operation ordering netfx/netcore
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2959 This one aligns var vs Type between netfx and netcore
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2960 Remove redundant Namespace to align netfx/netcore
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2961 Align ADP.IsEmpty -> string.IsNullOrEmpty
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2951 Fix SystemMemoryVersion variable missing
  tools/props/Versions.props
Labels: Common Project 🚮

#2975 docs: Update porting cheat sheet to include mention of backward incompable connection string changes
  porting-cheat-sheet.md
Labels: Area\Documentation

#2948 Replace public async void with public async Task for XUnit
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConfigurableRetryLogicTest.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ApiShould.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/AsyncTest/XmlReaderAsyncTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataReaderTest/DataReaderStreamsTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/MARSTest/MARSTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicCounterTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlCommandReliabilityTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_plus_sign: Code Health

#2944 Clean up build guide and docs after net6 removal
  BUILDGUIDE.md
  README.md
  contributing-workflow.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataStreamTest/DataStreamTest.cs
Labels: :heavy_plus_sign: Code Health

#2977 Remove NetStandard from AddOns scripts
  RunProjectReferenceTests.cmd
  buildAddons.cmd
Labels: Area\Engineering

#2966 Align comments between netfx and netcore codebases
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
Labels: Common Project 🚮

#2940 Remove SQLDebugging class
  doc/snippets/Microsoft.Data.SqlClient/SQLDebugging.xml
  src/Microsoft.Data.SqlClient.sln
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
Labels: :hammer: Breaking Change

#2978 Merge | Kernel32 Interop Namespace
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/LocalDB.Windows.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Crypt32/Interop.certificates.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Crypt32/Interop.certificates_types.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Handles/SafeLibraryHandle.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/FileTypes.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.CTL_CODE.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.CloseHandle.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.DeviceIoControl.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.FileTypes.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.FreeLibrary.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.GetFileType_SafeHandle.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.GetFullPathName.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.GetProcAddress.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.IoControlCodeAccess.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.IoControlTransferType.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.LoadLibraryEx.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Interop.SetThreadErrorMode.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/IoControlCodeAccess.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/IoControlTransferType.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Kernel32.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/Interop.NtCreateFile.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SystemErrors.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/UnicodeString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlFileStream.Windows.cs
Labels: Common Project 🚮

#2964 Complete port of PR 521 to netfx
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
Labels: NetFx :point_left: NetCore

#2862 Merge ContextConnection handling
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlCommandSet.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs
Labels: :new: Public API, :heavy_plus_sign: Code Health

#2983 Merge | Interop NtDll Namespace
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/CreateDisposition.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/CreateOptions.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/DesiredAccess.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/FileFullEaInformation.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ImpersonationLevel.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/Interop.FILE_FULL_EA_INFORMATION.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/Interop.IO_STATUS_BLOCK.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/Interop.NtCreateFile.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/Interop.RtlNtStatusToDosError.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/IoStatusBlock.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/NtDll.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ObjectAttributeFlags.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ObjectAttributes.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/SecurityQualityOfService.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SystemErrors.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlFileStream.Windows.cs
Labels: Common Project 🚮

#2994 Merge | Interop - SChannel, SspiCli, Unix, Move Interop_TEMP to Interop
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/LocalDB.Windows.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/NativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/SafeNativeMethods.cs
  src/Microsoft.Data.SqlClient/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Unix/System.Net.Security.Native/Interop.GssBuffer.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Handles/SafeLibraryHandle.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Interop.Libraries.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/FileTypes.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/IoControlCodeAccess.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/IoControlTransferType.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Kernel32.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/CreateDisposition.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/CreateOptions.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/DesiredAccess.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/FileFullEaInformation.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ImpersonationLevel.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/IoStatusBlock.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/NtDll.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ObjectAttributeFlags.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/ObjectAttributes.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/NtDll/SecurityQualityOfService.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/ApplicationProtocolNegotiationExt.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/ApplicationProtocolNegotiationStatus.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/Interop.SECURITY_STATUS.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/SecPkgContextApplicationProtocol.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/SecPkgContext_ConnectionInfo.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/GlobalSSPI.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/Interop.SSPI.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/NegotiationInfoClass.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SSPIAuthType.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SSPIInterface.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SSPISecureChannelType.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SSPIWrapper.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecPkgContext_Bindings.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecPkgContext_NegotiationInfoW.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecPkgContext_Sizes.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecPkgContext_StreamSizes.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecurityPackageInfo.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SspiCli/SecurityPackageInfoClass.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SystemErrors.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/UnicodeString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlFileStream.Windows.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.EndPoint/SSPI/SecurityWrapper.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.EndPoint/TDS.EndPoint.csproj
Labels: Common Project 🚮

#2955 Align whole comments between netfx and netcore
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2949 Move relative to absolute docs path
  doc/snippets/Microsoft.Data.Sql/SqlDataSourceEnumerator.xml
  doc/snippets/Microsoft.Data.Sql/SqlNotificationRequest.xml
  doc/snippets/Microsoft.Data.SqlClient.Server/SqlMetaData.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatch.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatchCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopy.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopyColumnMapping.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopyColumnOrderHint.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopyColumnOrderHintCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBulkCopyOptions.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlClientPermission.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlColumnEncryptionCertificateStoreProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlColumnEncryptionCngProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlColumnEncryptionCspProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlColumnEncryptionKeyStoreProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCommand.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCommandBuilder.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCommandColumnEncryptionSetting.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConfigurableRetryFactory.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionColumnEncryptionSetting.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCredential.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDataAdapter.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDataReader.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDependency.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlError.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlException.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlInfoMessageEventHandler.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlNotificationSource.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlParameter.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlParameterCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlRowUpdatedEventHandler.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlRowUpdatingEventHandler.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlTransaction.xml
  doc/snippets/Microsoft.Data.SqlTypes/SqlFileStream.xml
Labels: :heavy_plus_sign: Code Health

#2997 Merge | NativeMethods/SafeNativeMethods
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/NativeMethods.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/LocalDBAPI.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/AdvApi32/AdvApi32.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Kernel32.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Kernel32Safe.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolCounters.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
Labels: Common Project 🚮

#2991 Remove code that is unused in .NET 8
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Collections/Generic/BidirectionalDictionary.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/ContextFlagsAdapterPal.Unix.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/ContextFlagsAdapterPal.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/ContextFlagsPal.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/InternalException.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Logging/DebugThreadTracking.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Logging/NetEventSource.Common.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/NegotiationInfoClass.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/NegotiateStreamPal.Unix.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/NegotiateStreamPal.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/NetEventSource.Security.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/NetEventSource.Security.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/SecurityBuffer.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/Security/SecurityBufferType.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/SecurityStatusAdapterPal.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Net/SecurityStatusPal.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SspiClientContextStatus.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/SecPkgContextApplicationProtocol.netcore.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/ManagedSSPIContextProvider.cs
Labels: :heavy_plus_sign: Code Health

#2990 Code health - preprocessor directives
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ApiShould.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/CspProviderExt.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/DatabaseHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/CertificateUtilityWin.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/ProviderAgnostic/ReaderTest/ReaderTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataReaderTest/DataReaderStreamsTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DateTimeTest/DateTimeTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ParameterTest/ParametersTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicConfigHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/SqlDSEnumeratorTest/SqlDataSourceEnumeratorTest.cs
Labels: :heavy_plus_sign: Code Health

#2433 Add support for SqlConnectionOverrides for OpenAsync() API
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
Labels: :new: Public API

#2981 Remove SQL 2000 client-side debugging support
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/AdvApi32/AdvApi32.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Kernel32/Kernel32.cs
Labels: Common Project 🚮

#3008 Code Health | Remove unused/unreferenced files
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlTypes/SqlTypeWorkarounds.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlTypes/SqlFileStream.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/ApplicationProtocolNegotiationExt.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/SChannel/ApplicationProtocolNegotiationStatus.netcore.cs
Labels: :heavy_plus_sign: Code Health, Common Project 🚮

#3002 Merge | SNI Wrapper Class Extraction
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Common.cs
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/LocalDBAPI.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperARM64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX86.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/LocalDBAPI.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Common/Sni/SniErrors.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Secur32/ContextAttribute.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Secur32/CredHandle.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Secur32/Secur32.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/AuthProviderInfo.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/ConsumerInfo.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/ConsumerNumber.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/Delegates.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/IoType.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/Prefix.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/Provider.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/QueryType.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniClientConsumerInfo.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniConsumerInfo.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniDnsCacheInfo.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniError.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SqlDependencyProcessDispatcherStorage.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/TransparentNetworkResolutionMode.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
Labels: Common Project 🚮

#3017 Cleanup | Move SniErrors to be uint
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/LocalDBAPI.Common.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/LocalDBAPI.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/LocalDBAPI.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
Labels: :heavy_plus_sign: Code Health

#3032 SDL | Update SMO
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/Microsoft.Data.SqlClient.ExtUtilities.csproj
  tools/props/Versions.props
Labels: Area\Tests

#3026 Improve timeout of tests
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/ConversionTests.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/ColumnEncryptionKey.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/ColumnMasterKey.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/TracingTests/EventCounterTest.cs
Labels: Area\Tests

#2946 Add support for .NET 9
  build.proj
  eng/pipelines/common/templates/steps/ci-prebuild-step.yml
  eng/pipelines/common/templates/steps/ci-project-build-step.yml
  eng/pipelines/common/templates/steps/copy-dlls-for-test-step.yml
  eng/pipelines/common/templates/steps/prepare-test-db-step.yml
  eng/pipelines/dotnet-sqlclient-ci-core.yml
  eng/pipelines/dotnet-sqlclient-ci-package-reference-pipeline.yml
  eng/pipelines/dotnet-sqlclient-ci-project-reference-pipeline.yml
  eng/pipelines/libraries/mds-validation-variables.yml
  src/Directory.Build.props
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SqlNormalizer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
  src/Microsoft.Data.SqlClient/src/System/IO/StreamExtensions.netfx.cs
  src/Microsoft.Data.SqlClient/tests/Directory.Build.props
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/SqlColumnEncryptionCertificateStoreProviderShould.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/AlwaysEncryptedTests/Utility.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/CertificateUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Extensions/StreamExtensions.netfx.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectionTestWithSSLCert/CertificateTestWithTdsServer.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataStreamTest/DataStreamTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/SqlFileStreamTest/SqlFileStreamTest.cs
  src/Microsoft.Data.SqlClient/tests/PerformanceTests/Microsoft.Data.SqlClient.PerformanceTests.csproj
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/Microsoft.Data.SqlClient.ExtUtilities.csproj
  tools/props/Versions.props
  tools/props/VersionsNet8OrLater.props
Labels: :bulb: Enhancement

#3024 Add package vulnerability information
  NuGet.config
  src/Directory.Build.props
Labels: :heavy_plus_sign: Code Health

#2957 Merge | Align Type aliases between netfx and netcore
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2963 Merge | Align BitConverter/BinaryPrimitives usage netfx/netcore
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#2984 Merge | Move ReliabilitySection / BestEffortCleanup to framework specific files
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.netfx.cs
Labels: Common Project 🚮

#2982 Merge | Align Task usage / ArrayPool / IsColumnEncryptionSupported netcore/netfx
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: Common Project 🚮

#3023 Merge | Remove RelationshipConverter
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/RelationshipConverter.cs
Labels: :heavy_plus_sign: Code Health, Common Project 🚮

#3041 Update `DockerLinuxTest/Program.cs` reference
  BUILDGUIDE.md
Labels: Area\Documentation

#3015 Merge | SniNativeWrapper Interface
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Unix.cs
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/LocalDBAPI.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperARM64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX86.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/LocalDBAPI.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/ISniNativeMethods.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeMethods.netcore.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeMethodsArm64.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeMethodsNotSupported.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeMethodsX64.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeMethodsX86.netfx.cs
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeWrapper.cs
  src/Microsoft.Data.SqlClient/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Sql/SqlDataSourceEnumeratorNativeHelper.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NativeSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependency.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
  tools/props/Versions.props
Labels: Common Project 🚮
