Repository dotnet/SqlClient, pull requests merged in 2024-09, with the labels that each got.

#2801 Add streaming support for netcore and netfx
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/JsonTest/JsonStreamTest.cs
Labels: Json

#2821 Sample code improvements around token caching
  doc/samples/AzureKeyVaultProviderExample.cs
  doc/samples/AzureKeyVaultProviderWithEnclaveProviderExample.cs
  doc/samples/CustomDeviceCodeFlowAzureAuthenticationProvider.cs
  doc/samples/SqlConnection_AccessTokenCallback.cs
Labels: :page_with_curl: Documentation

#2826 Fix | Adding readme to nuget package
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :bulb: Enhancement

#2845 [5.2] | Fix strong name in AKV provider
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
Labels: :bug: Bug!, Infrastructure

#2846 [5.1] | Fix strong name in AKV provider
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
Labels: :bug: Bug!, Infrastructure

#2847 [4.0] | Fix strong name in AKV provider
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
Labels: :bug: Bug!, Infrastructure

#2848 [3.1] | Fix strong name in AKV provider
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
Labels: :bug: Bug!, Infrastructure

#2854 Update CDP_BUILD_TYPE condition in AKV provider
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
Labels: :heavy_plus_sign: Code Health

#2837 Doc | Sync sample changes into snippet doc
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationProvider.xml
Labels: :page_with_curl: Documentation

#2857 [5.2] Eng | Add CDP_BUILD_TYPE to package validator
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :bug: Bug!, Infrastructure

#2858 [5.1] Eng | Add CDP_BUILD_TYPE to package validator#2857
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :bug: Bug!, Infrastructure

#2859 [4.0] Eng | Add CDP_BUILD_TYPE to package validator
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :bug: Bug!, Infrastructure

#2860 [3.1] Eng | Add CDP_BUILD_TYPE to package validator
  eng/pipelines/common/templates/jobs/build-signed-package-job.yml
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :bug: Bug!, Infrastructure

#2863 XML Documentation Fixes - Batch 4
  doc/snippets/Microsoft.Data.SqlClient/SqlCommandBuilder.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCommandColumnEncryptionSetting.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConfigurableRetryFactory.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionAttestationProtocol.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionColumnEncryptionSetting.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionEncryptOption.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionIPAddressPreference.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionOverrides.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlCredential.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/ref/Microsoft.Data.SqlClient.Batch.NetCoreApp.cs
Labels: :page_with_curl: Documentation

#2865 XML Documentation Fixes - Batch 6
  doc/snippets/Microsoft.Data.SqlClient/SqlInfoMessageEventArgs.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlInfoMessageEventHandler.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlNotificationEventArgs.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlNotificationInfo.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlNotificationSource.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlNotificationType.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlParameter.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlParameterCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlRetryIntervalBaseEnumerator.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlRetryingEventArgs.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
Labels: :page_with_curl: Documentation

#2864 XML Documentation Fixes - Batch 5
  doc/snippets/Microsoft.Data.SqlClient/SQLDebugging.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlConnectionStringBuilder.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDataAdapter.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDataReader.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlDependency.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlEnclaveAttestationParameters.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlEnclaveSession.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlError.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlErrorCollection.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlException.xml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlException.cs
Labels: :page_with_curl: Documentation

#2871 XML Documentation Fixes - Batch 8
  doc/snippets/Microsoft.Data.Sql/SqlDataSourceEnumerator.xml
  doc/snippets/Microsoft.Data.Sql/SqlNotificationRequest.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/ColumnSensitivity.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/InformationType.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/Label.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityClassification.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityProperty.xml
  doc/snippets/Microsoft.Data.SqlClient.DataClassification/SensitivityRank.xml
  doc/snippets/Microsoft.Data.SqlClient.Server/SqlDataRecord.xml
  doc/snippets/Microsoft.Data.SqlClient.Server/SqlMetaData.xml
  doc/snippets/Microsoft.Data.SqlClient.Server/TriggerAction.xml
  doc/snippets/Microsoft.Data.SqlTypes/SqlFileStream.xml
  doc/snippets/Microsoft.Data/OperationAbortedException.xml
  doc/snippets/Microsoft.SqlServer.Server/DataAccessKind.xml
  doc/snippets/Microsoft.SqlServer.Server/Format.xml
  doc/snippets/Microsoft.SqlServer.Server/IBinarySerialize.xml
  doc/snippets/Microsoft.SqlServer.Server/InvalidUdtException.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlFacetAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlFunctionAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlMethodAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlUserDefinedAggregateAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SqlUserDefinedTypeAttribute.xml
  doc/snippets/Microsoft.SqlServer.Server/SystemDataAccessKind.xml
Labels: :page_with_curl: Documentation

#2836 XML documentation corrections - batch 1
  doc/samples/CustomDeviceCodeFlowAzureAuthenticationProvider.cs
  doc/samples/SqlBatch_ExecuteReader.cs
  doc/snippets/Microsoft.Data.SqlClient/PoolBlockingPeriod.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationInitializer.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationMethod.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationProvider.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlAuthenticationToken.xml
  doc/snippets/Microsoft.Data.SqlClient/SqlBatch.xml
Labels: :page_with_curl: Documentation

#2885 Fix | Documentation Build Breaks
  doc/snippets/Microsoft.Data.SqlClient.Server/SqlDataRecord.xml
  doc/snippets/Microsoft.Data.SqlClient.Server/SqlMetaData.xml
Labels: :page_with_curl: Documentation, :boom: Regression

#2882 Add streaming support for JSON
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/JsonTest/JsonStreamTest.cs
Labels: Json

#2880 Adding SqlJson and Data write with SqlJson (#2752)
  doc/snippets/Microsoft.Data.SqlTypes/SqlJson.xml
  src/Microsoft.Data.SqlClient.sln
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlJson.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/ManualTests/Json/SqlJsonTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
Labels: :new: Public API, Json

#2891 Enhancement tasks for json support
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/JsonTest/JsonTest.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.Servers/GenericTDSServer.cs
Labels: Json
