Repository dotnet/SqlClient, pull requests merged in 2024-05, with the labels that each got.

#2453 Fix | Fix DateTimeOffset size in TdsValueSetter.cs class file.
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsValueSetter.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UdtDateTimeOffsetTest.cs
Labels: :bug: Bug!

#2479 Test | Remove field with ClientSecretCredential type
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
Labels: :heavy_check_mark: Tests

#2474 Test | Remove AAS - VBS tests from test pipelines
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/SqlDbManager.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2447 Use memory/span for SSPI generation
  src/Microsoft.Data.SqlClient/netcore/src/Interop/SNINativeMethodWrapper.Windows.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperARM64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX64.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeManagedWrapperX86.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Interop/SNINativeMethodWrapper.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/ManagedSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NativeSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/SSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: :bug: Bug!

#2478 [5.1.6] Test | Updating tests to acquire token from user-assigned managed identity (#2360) (#2473)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/AKVUnitTests.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/CertificateUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/AADUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
  tools/props/Versions.props
Labels: :heavy_check_mark: Tests

#2485 [5.2.1] Tests | Remove test reference to deprecated ADAL library (#2360)
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/AADUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  tools/props/Versions.props
Labels: :heavy_check_mark: Tests

#2489 [5.2.1] Test | Remove AAS - VBS tests from test pipelines (#2474)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/SqlDbManager.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2490 [5.1.6] SDL | Changing ReadXml to a more secure overload (#2147)
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbMetaDataFactory.cs
Labels: :bulb: Enhancement

#2488 [5.2.1] Test | Updating tests to acquire token from user-assigned managed identity (#2473)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/AKVUnitTests.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/AlwaysEncrypted/TestFixtures/Setup/CertificateUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/SqlClientCustomTokenCredential.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2436 [5.2.1] | Regression | Revert PR #2281 SNIProxy code change (#2395)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
Labels: :boom: Regression

#2486 Streamline conditional compilation symbols
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Interop/Windows/Interop.Libraries.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/System/Net/Logging/NetEventSource.Common.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.AssemblyLoadContext.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDelegatedTransaction.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlTypes/SqlFileStream.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolAuthenticationContext.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Sql/SqlDataSourceEnumeratorNativeHelper.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalAppContextSwitches.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryLogicLoader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/ManagedSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SSPI/NegotiateSSPIContextProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlCommandBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependency.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.AssemblyLoadContext.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDependencyUtils.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsValueSetter.cs
  src/Microsoft.Data.SqlClient/src/Resources/StringsHelper.cs
  src/Microsoft.Data.SqlClient/src/System/Diagnostics/CodeAnalysis.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlErrorTest.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataReaderTest/DataReaderStreamsTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicConfigHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/TransactionTest/DistributedTransactionTest.cs
Labels: :heavy_plus_sign: Code Health

#2369 Merged SqlClientFactory between .NET Core and Framework
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientFactory.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientFactory.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlClientFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientFactory.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlClientFactoryTest.cs
Labels: :bulb: Enhancement, :heavy_plus_sign: Code Health

#2513 [4.0.6] | Fix CodeQL and Rozlyn warnings (#2428) and (#2432)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
Labels: :heavy_plus_sign: Code Health

#2506 [5.2.1] | Fix DateTimeOffset size in TdsValueSetter.cs class file. (#2453)
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsValueSetter.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UdtDateTimeOffsetTest.cs
Labels: :bug: Bug!

#2510 [4.0.6] | Test | Remove AAS - VBS tests from test pipelines (#2474)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/SqlDbManager.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2509 [5.1.6] | Test | Remove AAS - VBS tests from test pipelines (#2474)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/SqlDbManager.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2519 [4.0.6] | Fix Roslyn Analyzer Warning in 4.0
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIHandle.cs
Labels: :heavy_plus_sign: Code Health

#2515 [3.1.6] | Fix CodeQL and Rozlyn warnings (#2428) and (#2432)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
Labels: :heavy_plus_sign: Code Health

#2505 [5.2.1] | Fix SqlConnection.FireInfoMessageEventOnUserErrors when set to true throws an exception (#2399)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectivityTests/ConnectivityTest.cs
Labels: :bug: Bug!

#2511 [3.1.6] | Test | Remove AAS - VBS tests from test pipelines (#2474)
  BUILDGUIDE.md
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/SqlDbManager.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Config.cs
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/config.default.json
Labels: :heavy_check_mark: Tests

#2517 [3.1.6] | Address GenAPI tool CVE 2019-0545 & 2021-34485
  tools/GenAPI/Microsoft.DotNet.GenAPI/Microsoft.DotNet.GenAPI.csproj
Labels: Infrastructure

#2516 [3.1.6] SDL | Changing ReadXml to a more secure overload. (#2147)
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbMetaDataFactory.cs
Labels: :heavy_plus_sign: Code Health

#2514 [4.0.6] SDL | Changing ReadXml to a more secure overload. (#2147)
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbMetaDataFactory.cs
Labels: :heavy_plus_sign: Code Health

#2525 Fix | Clone of SqlConnection should include AccessTokenCallback
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/CloneTests.cs
Labels: :bug: Bug!

#2527 [5.2.1] | Clone of SqlConnection should include AccessTokenCallback
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/CloneTests.cs
Labels: :bug: Bug!

#2529 [5.1.6] Updating Azure.Identity version to 1.11.3
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
  tools/specs/add-ons/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.nuspec
Labels: :bulb: Enhancement

#2539 [3.1.6] | Suppress CodeQL X509RevocationMode warning
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/VirtualSecureModeEnclaveProviderBase.cs
Labels: :heavy_plus_sign: Code Health

#2537 Doc | Fix SNI dependencies of 5.1 and 5.2 release notes
  release-notes/5.1/5.1.0.md
  release-notes/5.1/5.1.1.md
  release-notes/5.1/5.1.2.md
  release-notes/5.1/5.1.3.md
  release-notes/5.1/5.1.4.md
  release-notes/5.1/5.1.5.md
  release-notes/5.2/5.2.0-preview1.md
  release-notes/5.2/5.2.0-preview2.md
  release-notes/5.2/5.2.0-preview3.md
  release-notes/5.2/5.2.0.md
Labels: :page_with_curl: Documentation

#2466 Change | Separate tests for NetFx and NetCore - NetFx-Only Connection String Properties
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionStringBuilderTest.cs
Labels: netfx

#2487 Fix | Enhance certificate validation
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNINpHandle.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionBasicTests.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/TestTdsServer.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/ConnectionTestParameters.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/ConnectionTestParametersData.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectionTestWithSSLCert/CertificateTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ConnectionTestWithSSLCert/CertificateTestWithTdsServer.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/TracingTests/TestTdsServer.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/makepfxcert.ps1
  src/Microsoft.Data.SqlClient/tests/ManualTests/mismatchedcert.cer
  src/Microsoft.Data.SqlClient/tests/ManualTests/removecert.ps1
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS/TDSStream.cs
Labels: :bulb: Enhancement, :m: Managed SNI

#2534 Hotfix v5.2.1 Release notes
  CHANGELOG.md
  release-notes/5.2/5.2.1.md
  release-notes/5.2/5.2.md
  release-notes/5.2/README.md
Labels: :page_with_curl: Documentation
