Repository dotnet/SqlClient, pull requests merged in 2024-08, with the labels that each got.

#2735 [5.2] Test | Fixed some Azure managed identity authentication unit test failures
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicTestHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2737 [4.0] Test | Fixed some Azure managed identity authentication unit test failures
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicTestHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2738 [5.1] Test | Fixed some Azure managed identity authentication unit test failures
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicTestHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2747 [3.1] eng | Fix strong name issue
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!, Infrastructure

#2746 [4.0] eng | Fix strong name issue
  eng/pipelines/common/templates/steps/build-all-configurations-signed-dlls-step.yml
  eng/pipelines/common/templates/steps/code-analyze-step.yml
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!, Infrastructure

#2739 Pool Warmup
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/PoolingDataSource.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/SqlConnector.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/SqlDataSource.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/SqlDataSourceBuilder.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClientX/UnpooledDataSource.cs
  src/Microsoft.Data.SqlClient/tests/UnitTests/PoolTests.cs
Labels: ClientX

#2740 [3.1] Test | Fixed some Azure managed identity authentication unit test failures
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/ExceptionTest/ExceptionTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/RetryLogicTestHelper.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/RetryLogic/SqlConnectionReliabilityTest.cs
Labels: :heavy_check_mark: Tests

#2752 Adding SqlJson and Data write with SqlJson
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlEnums.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlParameter.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlJson.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.Designer.cs
  src/Microsoft.Data.SqlClient/src/Resources/Strings.resx
  src/Microsoft.Data.SqlClient/tests/ManualTests/Json/SqlJsonTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
Labels: Json

#2772 Update SNI version to 6.0.0-preview1.24226.4
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :page_facing_up: Native SNI

#2775 [5.2] Add | Cache TokenCredential objects to take advantage of token caching (#2380)
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
Labels: :bulb: Enhancement

#2777 Fix | Fix the issue with Socke.Connect in managed SNI
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
Labels: :bug: Bug!, :m: Managed SNI, :boom: Regression

#2779 [5.2] Fix | Fix the issue with Socke.Connect in managed SNI (#2777)
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNICommon.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNITcpHandle.cs
Labels: :m: Managed SNI, :boom: Regression

#2776 [5.1] Add | Cache TokenCredential objects to take advantage of token caching (#2380)
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
Labels: :bulb: Enhancement

#2767 Hotfix v3.1.6 Release notes
  CHANGELOG.md
  release-notes/3.1/3.1.6.md
  release-notes/3.1/3.1.md
  release-notes/3.1/README.md
Labels: :page_with_curl: Documentation

#2781 [4.0] Fix | Enable source link translation
  src/Directory.Build.props
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  tools/props/Versions.props
  tools/targets/RepositoryInfo.targets
Labels: :bug: Bug!

#2780 [5.1] Backport SourceLink translation
  src/Directory.Build.props
  src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.SqlServer.Server/Microsoft.SqlServer.Server.csproj
  tools/props/Versions.props
  tools/targets/RepositoryInfo.targets
Labels: :bug: Bug!

#2789 [5.2] Fix | Adjust path for .AssemblyAttributes in obj folder (#2550)
  src/Microsoft.Data.SqlClient/add-ons/Directory.Build.props
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2791 Doc | Reorder release notes
  CHANGELOG.md
  release-notes/5.2/5.2.0.md
  release-notes/5.2/5.2.1.md
Labels: :page_with_curl: Documentation

#2798 [3.1] Remove delaySign
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2794 [5.2] Remove delay signed
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2796 [4.0] Remove delay signed
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!

#2800 Hotfix v3.1.7 Release notes
  CHANGELOG.md
  release-notes/3.1/3.1.7.md
  release-notes/3.1/3.1.md
  release-notes/3.1/README.md
Labels: :page_with_curl: Documentation

#2802 Eng | Add strong name validation to package validator
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: Infrastructure

#2803 [5.2] Eng | Add strong name validation to package validator (#2802)
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :heavy_check_mark: Tests, Infrastructure

#2390 Merged PoolWaitHandles, DbConnectionPoolIdentity, removed DbBuffer
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbBuffer.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.Unix.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.cs
Labels: :heavy_plus_sign: Code Health

#2806 [3.1] Eng | Add strong name validation to package validator (#2802)
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :heavy_check_mark: Tests, Infrastructure

#2807 [4.0] Eng | Add strong name validation to package validator (#2802)
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :heavy_check_mark: Tests, Infrastructure

#2795 [5.1] Remove delay signed
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
Labels: :bug: Bug!, Infrastructure

#2768 Hotfix v4.0.6 Release notes
  CHANGELOG.md
  release-notes/4.0/4.0.6.md
  release-notes/4.0/4.0.md
  release-notes/4.0/README.md
Labels: :page_with_curl: Documentation

#2811 Refine version.props and nuspec files
  tools/props/Versions.props
  tools/props/VersionsNet8OrLater.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: :heavy_plus_sign: Code Health

#2815 [5.2] Fix GenerateSspiClientContext to retry negotiation with default port
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs
Labels: :bug: Bug!, netcore

#2816 [5.2.2] | Fix ArgumentNullException on SqlDataRecord.GetValue when using Udt data type
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/MetadataUtilsSmi.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlDataRecordTest.cs
Labels: :bug: Bug!

#2817 [5.2.2] | Fix decrypt failure to drain data
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: :bug: Bug!

#2410 Merged DbConnectionClosed, DbConnectionFactory, SqlAuthenticationProviderManager
  src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionClosed.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionClosed.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionClosed.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs
Labels: :heavy_plus_sign: Code Health

#2818 [5.1.6] | Fix decrypt failure to drain data
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
Labels: :bug: Bug!

#2804 [5.1] Eng | Add strong name validation to package validator (#2802)
  eng/pipelines/common/templates/jobs/validate-signed-package-job.yml
Labels: :heavy_check_mark: Tests, Infrastructure

#2769 Hotfix v5.1.6 Release notes
  CHANGELOG.md
  release-notes/5.1/5.1.6.md
  release-notes/5.1/5.1.md
  release-notes/5.1/README.md
Labels: :page_with_curl: Documentation

#2770 Hotfix v5.2.2 Release notes
  CHANGELOG.md
  release-notes/5.2/5.2.2.md
  release-notes/5.2/5.2.md
  release-notes/5.2/README.md
Labels: :page_with_curl: Documentation

#2820 Add porting information about NLS to ICU .NET 5+ change
  porting-cheat-sheet.md
Labels: :bug: Bug!, :page_with_curl: Documentation

#2813 Doc | Release notes v6.0 preview1
  CHANGELOG.md
  release-notes/6.0/6.0.0-preview1.md
  release-notes/6.0/6.0.md
  release-notes/6.0/README.md
Labels: :page_with_curl: Documentation

#2442 Test | Fix Unit Tests for GetSqlServerSPN
  src/Microsoft.Data.SqlClient/tests/ManualTests/DataCommon/DataTestUtility.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/DataSourceParserTest/DataSourceParserTest.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/InstanceNameTest/InstanceNameTest.cs
Labels: :heavy_check_mark: Tests

#2773 Add Feature Extension for Json Support
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsEnums.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.EndPoint/ITDSServerSession.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.Servers/GenericTDSServer.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.Servers/GenericTDSServerSession.cs
  src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS/TDSFeatureID.cs
Labels: Json
