Repository dotnet/SqlClient, pull requests merged in 2025-05, with the labels that each got.

#3306 Merge | SqlFileStream.Unix
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlFileStream.Unsupported.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlFileStream.netcore.Unix.cs
Labels: Common Project 🚮

#3322 Engineering | Nuget Audit Sources Fix
  src/Directory.Build.props
Labels: Area\Engineering

#3318 Backport 5.1 | Nuget Audit Sources
  src/Directory.Build.props
Labels: Area\Engineering

#3320 Backport 5.2 | Nuget Audit Sources
  src/Directory.Build.props
Labels: Area\Engineering

#3262 Merge | SqlClientPermission
  src/Microsoft.Data.SqlClient/netfx/src/Common/Microsoft/Data/Common/NameValuePermission.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlClientPermission.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientPermission.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientPermissionAttribute.netfx.cs
Labels: Common Project 🚮

#3326 Merge | Netfx SMI Classes
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/Server/SmiConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/Server/SmiRequestExecutor.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/Server/SmiXetterAccessMap.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/Server/TriggerAction.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiConnection.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiContext.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiContextFactory.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiEventSink_DeferredProcessing.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiEventStream.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiExecuteType.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiLink.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiRequestExecutor.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiStream.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiXetterAccessMap.Common.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/SmiXetterAccessMap.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/TriggerAction.netfx.cs
Labels: Common Project 🚮

#3335 Merge | SqlDataSourceEnumerator.Unix.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Sql/SqlDataSourceEnumerator.netcore.Unix.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Sql/SqlDataSourceEnumeratorManagedHelper.netcore.cs
Labels: Common Project 🚮

#3338 Cleanup | Interop Path Links
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
Labels: Code Health :pill:

#3340 Merge | Delete NotImplemented.cs
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/NotImplemented.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
Labels: Common Project 🚮

#3341 Merge | SessionHandle, TdsParserStateObject
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObjectNative.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SessionHandle.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SessionHandle.netcore.Unix.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: Common Project 🚮

#3323 Merge | SqlInternalConnectionTds preparation
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
Labels: Common Project 🚮

#3368 Merge | SqlBuffer
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBuffer.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlBuffer.cs
Labels: Common Project 🚮

#3353 Merge | TdsParserStateObject PacketHandle usage
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/PacketHandle.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/PacketHandle.netcore.Unix.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserSafeHandles.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.Multiplexer.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/TdsParserStateObject.TestHarness.cs
Labels: Common Project 🚮

#3343 Merge | DbConnectionOptions Prep Work
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/Common/ConnectionString/DbConnectionOptions.netcore.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionHelper.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/ConnectionString/DbConnectionOptions.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionHelper.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionOptions.Debug.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionOptions.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionClosed.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/DbConnectionPoolGroup.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/IDbConnectionPool.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/WaitHandleDbConnectionPool.cs
Labels: Common Project 🚮
