Repository dotnet/SqlClient, pull requests merged in 2025-02, with the labels that each got.

#3133 Cleanup | Solution Folders
  src/Microsoft.Data.SqlClient.sln
Labels: :heavy_plus_sign: Code Health

#3143 [5.1] Look for nuget config in root
  eng/pipelines/common/templates/steps/update-nuget-config-local-feed-step.yml
Labels: Area\Engineering

#3144 [5.2] Look for nuget config in root
  eng/pipelines/common/templates/steps/update-nuget-config-local-feed-step.yml
Labels: Area\Engineering

#3164 Cleanup/Merge | Remove Reliability Section
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.netcore.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObject.netcore.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlTransaction.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParser.netfx.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlCommandBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDelegatedTransaction.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalConnection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlInternalTransaction.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserStateObject.cs
Labels: :heavy_plus_sign: Code Health, Common Project 🚮

#3178 Fix | Remove TargetFramework From ExtUtilities Project
  src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.ExtUtilities/Microsoft.Data.SqlClient.ExtUtilities.csproj
Labels: :bug: Bug!, Area\Tests, Area\Engineering

#3171 Merge | LocalDbConfig
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/LocalDBConfig.cs
  src/Microsoft.Data.SqlClient/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalDBAPI.Windows.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalDb/LocalDbConfigurationSection.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalDb/LocalDbInstanceElement.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalDb/LocalDbInstancesCollection.netfx.cs
Labels: Common Project 🚮

#3150 AKV Official Pipeline
  build.proj
  eng/pipelines/akv-official-pipeline.yml
  eng/pipelines/jobs/build-akv-official-job.yml
  eng/pipelines/steps/compound-build-akv-step.yml
  eng/pipelines/steps/compound-esrp-code-signing-step.yml
  eng/pipelines/steps/compound-extract-akv-apiscan-files-step.yml
  eng/pipelines/steps/compound-nuget-pack-step.yml
  eng/pipelines/steps/compound-publish-symbols-step.yml
  eng/pipelines/steps/roslyn-analyzers-akv-step.yml
  eng/pipelines/steps/script-output-environment-variables-step.yml
  eng/pipelines/variables/akv-official-variables.yml
  eng/pipelines/variables/common-variables.yml
  eng/pipelines/variables/onebranch-variables.yml
  src/Directory.Build.props
  src/Microsoft.Data.SqlClient.sln
Labels: Area\Engineering
