Repository dotnet/SqlClient, pull requests merged in 2025-01, with the labels that each got.

#2967 Merge | Add IDBColumnSchemaGenerator interface to netfx SqlDataReader
  src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.cs
  src/Microsoft.Data.SqlClient/netfx/ref/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDbColumn.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParserHelperClasses.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/SqlServerTypesTest.cs
  tools/props/Versions.props
  tools/specs/Microsoft.Data.SqlClient.nuspec
Labels: Common Project 🚮

#3019 Preserve distributed transactions on pooled connection reset
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/TransactionTest/DistributedTransactionTest.Windows.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/TransactionTest/DistributedTransactionTest.cs
Labels: :bug: Bug!

#3131 Release Notes for v6.0.1
  CHANGELOG.md
  README.md
  release-notes/3.1/3.1.2.md
  release-notes/3.1/3.1.3.md
  release-notes/3.1/3.1.4.md
  release-notes/3.1/3.1.5.md
  release-notes/3.1/3.1.7.md
  release-notes/5.1/5.1.0-preview2.md
  release-notes/5.1/5.1.0.md
  release-notes/5.1/5.1.1.md
  release-notes/5.1/5.1.2.md
  release-notes/5.1/5.1.3.md
  release-notes/5.1/5.1.4.md
  release-notes/5.1/5.1.5.md
  release-notes/5.1/5.1.6.md
  release-notes/5.2/5.2.0-preview1.md
  release-notes/5.2/5.2.0-preview2.md
  release-notes/5.2/5.2.0-preview3.md
  release-notes/5.2/5.2.0-preview4.md
  release-notes/5.2/5.2.0-preview5.md
  release-notes/5.2/5.2.0.md
  release-notes/5.2/5.2.1.md
  release-notes/5.2/5.2.2.md
  release-notes/6.0/6.0.0-preview1.md
  release-notes/6.0/6.0.0-preview2.md
  release-notes/6.0/6.0.0-preview3.md
  release-notes/6.0/6.0.0.md
  release-notes/6.0/6.0.1.md
  release-notes/6.0/6.0.md
  release-notes/6.0/README.md
  release-notes/README.md
Labels: Area\Documentation
