Repository dotnet/SqlClient, pull requests merged in 2025-04, with the labels that each got.

#2728 [5.1] Fix | Dotnet build command
  build.proj
Labels: Bug! :bug:

#3247 Merge | SessionHandle.*.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SessionHandle.netcore.Unix.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SessionHandle.netcore.Windows.cs
Labels: Common Project 🚮

#3254 Merge/Cleanup | GreenMethods
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/GreenMethods.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientFactory.cs
Labels: Common Project 🚮

#3259 Merge | SqlDataReader
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlCommand.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlDataReader.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/TdsParserStateObject.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlDataReader.cs
Labels: Common Project 🚮

#3264 Merge | BufferWriterExtensions
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIPhysicalHandle.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Interop/Windows/Sni/SniNativeWrapper.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlObjectPools.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsParser.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Utilities/BufferWriterExtensions.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Utilities/ObjectPool.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Utilities/ObjectPools.cs
  src/Microsoft.Data.SqlClient/src/System/Buffers/ArrayBufferWriter.netfx.cs
Labels: Common Project 🚮

#3256 Merge | DbConnectionString.Common
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/Common/DbConnectionOptions.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/DBConnectionString.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/Common/DbConnectionOptions.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/AdapterUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/AttestationProtocolUtilities.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionStringDefaults.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionStringKeywords.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionStringSynonyms.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/DbConnectionStringUtilities.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/IpAddressPreferenceUtilities.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/ConnectionString/PoolBlockingUtilities.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionOptions.Common.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionString.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlConnectionStringBuilder.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlUtil.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/TdsEnums.cs
Labels: Common Project 🚮

#3251 Merge | Merge metrics/performance counter methodology
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientEventSource.NetCoreApp.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/ProviderBase/DbConnectionInternal.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/DbConnectionPool.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/DbConnectionPoolCounters.netfx.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/DbConnectionPoolGroup.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ConnectionPool/WaitHandleDbConnectionPool.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Diagnostics/SqlClientMetrics.cs
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/TracingTests/MetricsTest.cs
Labels: Common Project 🚮

#3275 Merge | SqlConnection cosmetic changes
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs
  src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlConnection.cs
Labels: Code Health :pill:

#3263 Merge | TaskToApm
  src/Microsoft.Data.SqlClient/netcore/src/Common/System/Threading/Tasks/TaskToApm.cs
  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
  src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlSequentialStream.cs
Labels: Common Project 🚮

#3175 Pipelines | Fix dotnet Installation on ARM64
  eng/pipelines/common/templates/jobs/ci-code-coverage-job.yml
  eng/pipelines/common/templates/jobs/ci-run-tests-job.yml
  eng/pipelines/common/templates/steps/ci-prebuild-step.yml
  eng/pipelines/common/templates/steps/ci-project-build-step.yml
  eng/pipelines/common/templates/steps/ensure-dotnet-version.yml
  eng/pipelines/common/templates/steps/pre-build-step.yml
  src/Microsoft.Data.SqlClient.sln
Labels: Area\Engineering

#3312 Tests | Update Package Versions
  src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj
  src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj
  tools/props/Versions.props
Labels: Area\Tests
